import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {loginDatabase} from './helpers/loginDatabase.js';
import {getEquipmentRequests,saveEquipmentRequest,removeEquipmentRequest,listEquipmentRequestEvents} from '../src/modules/equipmentSupport/requests.js';
import type {AuthenticatedUser} from '../src/modules/accessControl/types.js';
test('TC_E07S02_01 TC_E07S02_02 TC_E07S02_03 TC_E07S02_04 real event equipment request persistence, notifications and guards',async()=>{
  const db=await loginDatabase();const q=db.pool.query.bind(db.pool);const coord=randomUUID(),other=randomUUID(),tech=randomUUID(),inactive=randomUUID(),org=randomUUID(),organiser=randomUUID(),a=randomUUID(),b=randomUUID(),draft=randomUUID(),wrong=randomUUID(),equipment=randomUUID(),projector=randomUUID();
  const actor:AuthenticatedUser={id:coord,email:'coord@example.test',role:'event_coordinator',isActive:true,failedLoginCount:0};
  try{
    await q("INSERT INTO client_organisations(id,name) VALUES ($1,'Equipment request test')",[org]);
    for(const [id,role,active] of [[coord,'event_coordinator',true],[other,'event_coordinator',true],[tech,'technical_support_staff',true],[inactive,'technical_support_staff',false],[organiser,'event_organiser',true]]) await q(`INSERT INTO users(id,email,password_hash,full_name,role,is_active,client_org_id) VALUES($1,$2,'unused','Synthetic user',$3,$4,$5)`,[id,`${id}@example.test`,role,active,org]);
    const range=`[${new Date(Date.now()+86400000).toISOString()},${new Date(Date.now()+90000000).toISOString()})`;
    for(const [id,code,status,owner] of [[a,'EVT-A','planning',coord],[b,'EVT-B','approved',coord],[draft,'EVT-DRAFT','draft',coord],[wrong,'EVT-WRONG','planning',other]]) await q(`INSERT INTO events(id,event_code,organiser_id,coordinator_id,client_org_id,title,event_range,expected_attendance,status) VALUES($1,$2,$3,$4,$5,$2,$6::tstzrange,10,$7)`,[id,code,organiser,owner,org,range,status]);
    for(const [id,name,stock] of [[equipment,'Wireless Microphone',10],[projector,'Projector',2]]) await q(`INSERT INTO equipment(id,name,category,description,total_quantity,home_location,operational_status) VALUES($1,$2,'Audio','Synthetic',$3,'Test Storage','available')`,[id,name,stock]);
    const input={equipmentId:equipment,quantity:2,notes:'Handheld'};
    const created=await saveEquipmentRequest(db.pool,actor,'EVT-A',input);assert.equal(created.status,201);const id=created.body.requestId!;
    assert.equal((await saveEquipmentRequest(db.pool,actor,'EVT-A',{equipmentId:projector,quantity:1})).status,201);
    assert.equal((await getEquipmentRequests(q,actor,'EVT-A')).requests.length,2);
    assert.equal((await getEquipmentRequests(q,actor,'EVT-B')).requests.length,0);
    assert.equal((await q('SELECT count(*)::int AS n FROM notifications WHERE user_id=$1',[tech])).rows[0].n,2);
    assert.equal((await q('SELECT count(*)::int AS n FROM notifications WHERE user_id=$1',[inactive])).rows[0].n,0);
    assert.equal((await q('SELECT count(*)::int AS n FROM notification_deliveries')).rows[0].n,2);
    const excessive=await saveEquipmentRequest(db.pool,actor,'EVT-A',{...input,quantity:15},id);assert.equal(excessive.status,200);assert.deepEqual(excessive.body.warning,{name:'Wireless Microphone',requested:15,totalStock:10});
    assert.equal((await getEquipmentRequests(q,actor,'EVT-A')).requests.find(r=>r.id===id)?.quantity,15);
    const notices=(await q('SELECT count(*)::int AS n FROM notifications')).rows[0].n;
    const unchanged=await saveEquipmentRequest(db.pool,actor,'EVT-A',{...input,quantity:15},id);assert.equal(unchanged.body.changed,false);assert.equal((await q('SELECT count(*)::int AS n FROM notifications')).rows[0].n,notices);
    assert.equal((await saveEquipmentRequest(db.pool,actor,'EVT-A',input)).status,409);
    await assert.rejects(saveEquipmentRequest(db.pool,actor,'EVT-B',input,id),{status:404});
    await assert.rejects(saveEquipmentRequest(db.pool,actor,'EVT-DRAFT',input),{status:409});
    await assert.rejects(saveEquipmentRequest(db.pool,actor,'EVT-WRONG',input),{status:403});
    await assert.rejects(getEquipmentRequests(q,{...actor,id:other},'EVT-A'),{status:403});
    assert.equal((await q("SELECT count(*)::int AS n FROM audit_logs WHERE action='Access Denied'")).rows[0].n,2);
    const changed=await saveEquipmentRequest(db.pool,actor,'EVT-A',{...input,quantity:3},id);assert.equal(changed.status,200);
    await q(`CREATE FUNCTION reject_request_delivery() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic outbox failure'; END $$`);await q('CREATE TRIGGER reject_request_delivery BEFORE INSERT ON notification_deliveries FOR EACH ROW EXECUTE FUNCTION reject_request_delivery()');
    await assert.rejects(saveEquipmentRequest(db.pool,actor,'EVT-A',{...input,quantity:4},id),/synthetic outbox failure/);
    await assert.rejects(removeEquipmentRequest(db.pool,actor,'EVT-A',id),/synthetic outbox failure/);
    assert.equal((await getEquipmentRequests(q,actor,'EVT-A')).requests.find(r=>r.id===id)?.quantity,3);
    await q('DROP TRIGGER reject_request_delivery ON notification_deliveries');
    await q(`INSERT INTO equipment_reservations(request_id,event_id,equipment_id,quantity_reserved,reservation_range,reserved_by) VALUES($1,$2,$3,2,$4::tstzrange,$5)`,[id,a,equipment,range,tech]);
    await assert.rejects(saveEquipmentRequest(db.pool,actor,'EVT-A',{...input,quantity:4},id),{status:409});
    await assert.rejects(removeEquipmentRequest(db.pool,actor,'EVT-A',id),{status:409});
    assert.equal((await getEquipmentRequests(q,actor,'EVT-A')).requests.find(r=>r.id===id)?.reserved,true);
    const otherRequest=(await getEquipmentRequests(q,actor,'EVT-A')).requests.find(r=>r.equipmentId===projector)!;
    await removeEquipmentRequest(db.pool,actor,'EVT-A',otherRequest.id);assert.equal((await getEquipmentRequests(q,actor,'EVT-A')).requests.length,1);
    await saveEquipmentRequest(db.pool,actor,'EVT-B',{equipmentId:projector,quantity:1});
    assert.equal((await getEquipmentRequests(q,actor,'EVT-A')).requests[0].quantity,3);
    const support=await getEquipmentRequests(q,{...actor,id:tech,role:'technical_support_staff'},'EVT-A');assert.equal(support.canEdit,false);
    assert.equal((await listEquipmentRequestEvents(q,{...actor,id:tech,role:'technical_support_staff'})).events.length,2);
    await assert.rejects(saveEquipmentRequest(db.pool,{...actor,id:tech,role:'technical_support_staff'},'EVT-A',input),{status:403});
    await q('UPDATE equipment SET is_active=false WHERE id=$1',[projector]);await assert.rejects(saveEquipmentRequest(db.pool,actor,'EVT-A',{equipmentId:projector,quantity:1}),{status:409});
    // Concurrent creates serialize on the event and cannot duplicate a line.
    await q('UPDATE equipment SET is_active=true WHERE id=$1',[projector]);
    const concurrent=await Promise.all([saveEquipmentRequest(db.pool,actor,'EVT-A',{equipmentId:projector,quantity:1}),saveEquipmentRequest(db.pool,actor,'EVT-A',{equipmentId:projector,quantity:1})]);assert.deepEqual(concurrent.map(x=>x.status).sort(),[201,409]);
  }finally{await db.close();}
});
